version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers
    steps:
      - checkout
      - run: cd back-end/
      - run: ls
      - run: composer global require laravel/installer
      - run: composer install -n --prefer-dist
      # run tests!      
      - run: ./vendor/bin/phpcs -n --standard=phpcs.xml

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:71:d5:92:8f:cd:dd:6f:0f:d1:14:ae:fe:fe:70:27"
      - run:
          name: Deploy Over SSH
          command: ssh -tt rsa_dungle@35.240.201.198 "cd /var/www/intern/back-end && bash ./build.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      # - deploy:
      #     require:
      #       build
      #     filters:
      #       branches:
      #         only: dev-be

